services:
  spring:
    build:
      context: .
      target: test
    ports:
      - "8080:8080"
    environment:
      - SERVER_PORT=8080
      - MYSQL_URL=jdbc:mysql://db:3306/app
    volumes:
      - ./:/app
    depends_on:
      - db
    networks:
      - mynetwork
  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./src/main/resources/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=app
    networks:
      - mynetwork
volumes:
  mysql_data:
networks:
  mynetwork:
    driver: bridge