services:
  spring:
    build:
      context: ./backend
      target: dev
    ports:
      - "8080:8080"
    environment:
      - SERVER_PORT=8080
      - MYSQL_URL=jdbc:mysql://db:3306/app
    volumes:
      - ./backend:/app/backend
    depends_on:
      - db
    networks:
      - mynetwork
    expose:
      - 8080

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app/frontend
    expose:
      - 3000

  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./backend/src/main/resources/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=app
    networks:
      - mynetwork
      
volumes:
  mysql_data:
networks:
  mynetwork:
    driver: bridge